name: HTML5 Validator
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: .
        
    - uses: actions/upload-artifact@v3
    - name: Logs
      with:
        name: log
        path: log.log
